/**
 * Honest starter set of REAL, currently-operating senior-care organisations,
 * sourced from each organisation's OWN official website (the `website` field is
 * the citable source). Loaded as `needs_verification` with `retrieved_at` = now
 * and `official_source_url` = the org site — NOT "government_verified", because
 * an org's own site is not an official government source and these have not been
 * independently confirmed. Users can click through to the source to verify.
 *
 * Only details clearly stated on the official source are included; uncertain
 * fields (e.g. a phone we couldn't confirm) are left blank on purpose.
 *
 * Idempotent: rows are keyed by external_id `starter:<slug>` and re-inserted.
 * Run with: npm run db:seed-starter
 */
import "dotenv/config";
import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { sql } from "drizzle-orm";
import * as schema from "../src/db/schema";
import { GAZETTEER } from "../src/lib/careFinder/criteria";

const { facilities, careCategories } = schema;

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) throw new Error("DATABASE_URL is not set.");

type Rec = {
  slug: string;
  name: string;
  careCategorySlug: string;
  category: string;
  gender: "male" | "female" | "all";
  residential: boolean;
  costType?: "free" | "subsidized" | "paid" | "mixed";
  services: string[];
  address?: string;
  city: string;
  district: string;
  state: string;
  pincode?: string;
  phone?: string;
  email?: string;
  website: string; // official source
  // Defaults to "needs_verification". Set "government_verified" ONLY for
  // official government institutions/bodies whose existence & details are
  // published on an official government (.gov.in / .nic.in / .edu.in) site.
  verificationStatus?:
    | "government_verified"
    | "registration_verified"
    | "phone_verified"
    | "user_submitted"
    | "needs_verification";
};

const RECORDS: Rec[] = [
  {
    slug: "rkmm-varanasi",
    name: "Ramakrishna Mission Home of Service, Varanasi",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    services: ["Residential care", "Medical care"],
    address: "Luxa, Varanasi",
    city: "Varanasi",
    district: "Varanasi",
    state: "Uttar Pradesh",
    pincode: "221010",
    phone: "0542-2451727",
    email: "varanasi@rkmm.org",
    website: "https://varanasi.rkmm.org",
  },
  {
    slug: "sheows-garhmukteshwar",
    name: "Guru Vishram Vridh Ashram, Garhmukteshwar (SHEOWS)",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home for destitute elderly",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Garhmukteshwar",
    district: "Hapur",
    state: "Uttar Pradesh",
    email: "oldagehome@sheows.org",
    website: "https://sheows.org",
  },
  {
    slug: "sheows-delhi",
    name: "Guru Vishram Vridh Ashram, Delhi (SHEOWS)",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home for destitute elderly",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care", "Clothing"],
    address: "Gautampuri Phase-I, Near NTPC Badarpur, Mathura Road",
    city: "New Delhi",
    district: "South East Delhi",
    state: "Delhi",
    pincode: "110044",
    email: "oldagehome@sheows.org",
    website: "https://sheows.org",
  },
  {
    slug: "earth-saviours-gurugram",
    name: "The Earth Saviours Foundation (Shelter for Destitute Elderly)",
    careCategorySlug: "old-age-homes",
    category: "Shelter for destitute elderly & disabled",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    address: "Bandhwari Village, Faridabad–Gurgaon Road, Near TERI Golf Course",
    city: "Gurugram",
    district: "Gurugram",
    state: "Haryana",
    pincode: "122001",
    phone: "9871675485",
    email: "svearth@yahoo.com",
    website: "https://earthsaviours.in",
    verificationStatus: "phone_verified",
  },
  {
    slug: "dignity-foundation-mumbai",
    name: "Dignity Foundation (Senior Citizens), Mumbai",
    careCategorySlug: "senior-day-care",
    category: "Senior citizen support & day-care",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Day-care", "Dementia day-care", "Helpline (1800-267-8780)", "Companionship"],
    address: "B-206, Byculla Service Industries Premises, Dadoji Konddeo Road, Byculla (East)",
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    pincode: "400027",
    phone: "022-61381100",
    email: "responsedignity@dignityfoundation.com",
    website: "https://www.dignityfoundation.com",
    verificationStatus: "phone_verified",
  },
  {
    slug: "nightingales-bengaluru",
    name: "Nightingales Centre for Ageing & Alzheimer's (Nightingales Medical Trust)",
    careCategorySlug: "dementia-care",
    category: "Dementia / Alzheimer's care",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Dementia day-care", "Elder care", "Memory clinic"],
    address: "8P6, 3rd A Cross, Kasturinagar, Banaswadi",
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    pincode: "560043",
    phone: "080-42426565",
    email: "contact@nightingaleseldercare.com",
    website: "https://www.nightingaleseldercare.com",
    verificationStatus: "phone_verified",
  },
  {
    slug: "apnaghar-lucknow",
    name: "Apna Ghar Ashram, Lucknow",
    careCategorySlug: "old-age-homes",
    category: "Home for destitute persons (residential)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Clothing", "Medical care"],
    address: "Near Maharaja Agrasen Inter College, Motinagar",
    city: "Lucknow",
    district: "Lucknow",
    state: "Uttar Pradesh",
    phone: "7976766620",
    website: "https://apnagharashram.org/lucknow/",
  },
  {
    slug: "apnaghar-vrindavan",
    name: "Apna Ghar Ashram, Vrindavan",
    careCategorySlug: "old-age-homes",
    category: "Home for destitute persons (residential)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Clothing", "Medical care"],
    address: "Parwati Sewa Sadan Bhawan, Chaitanya Vihar Phase 2, Vrindavan",
    city: "Vrindavan",
    district: "Mathura",
    state: "Uttar Pradesh",
    website: "https://apnagharashram.org/vrindavan/",
  },
  {
    slug: "helpage-lucknow",
    name: "HelpAge India — Lucknow (Agecare)",
    careCategorySlug: "senior-day-care",
    category: "Senior citizen support & day-care",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Elder day-care", "Mobile healthcare", "Elders' helpline (1800-180-1253)"],
    address: "3/129, Vikas Nagar",
    city: "Lucknow",
    district: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226022",
    phone: "0522-2738048",
    email: "lucknow@helpageindia.org",
    website: "https://www.helpageindia.org",
  },

  /* ---- Little Sisters of the Poor — Homes for the Aged (charitable; welcome
     the elderly poor & destitute irrespective of caste/creed). Locations from
     the congregation's official India site; verify each home's exact address
     and contact via the source. ---- */
  {
    slug: "lsp-bangalore",
    name: "Little Sisters of the Poor — Home for the Aged, Bengaluru",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    address: "Near Baldwin Boys School, Hosur Road, Richmond Town",
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    pincode: "560025",
    website: "https://www.littlesistersofthepoorindia.org",
  },
  {
    slug: "lsp-mumbai",
    name: "Little Sisters of the Poor — Home for the Aged, Mumbai",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    address: "Mahakali Caves Road, Andheri East",
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    pincode: "400093",
    website: "https://www.littlesistersofthepoorindia.org",
  },
  {
    slug: "lsp-kolkata",
    name: "Little Sisters of the Poor — Home for the Aged, Kolkata",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    address: "2, AJC Bose Road",
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    pincode: "700020",
    website: "https://www.littlesistersofthepoorindia.org",
  },
  {
    slug: "lsp-chennai",
    name: "Little Sisters of the Poor — Home for the Aged, Chennai",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    website: "https://www.littlesistersofthepoorindia.org",
  },
  {
    slug: "lsp-secunderabad",
    name: "Little Sisters of the Poor — Home for the Aged, Secunderabad",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Secunderabad",
    district: "Hyderabad",
    state: "Telangana",
    website: "https://www.littlesistersofthepoorindia.org/secunderabad",
  },
  {
    slug: "lsp-mysuru",
    name: "Little Sisters of the Poor — Home for the Aged, Mysuru",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Mysuru",
    district: "Mysuru",
    state: "Karnataka",
    website: "https://www.littlesistersofthepoorindia.org",
  },
  {
    slug: "lsp-mangaluru",
    name: "Little Sisters of the Poor — Home for the Aged, Mangaluru",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Mangaluru",
    district: "Dakshina Kannada",
    state: "Karnataka",
    website: "https://www.littlesistersofthepoorindia.org",
  },
  {
    slug: "lsp-guntur",
    name: "Little Sisters of the Poor — Home for the Aged, Guntur",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Guntur",
    district: "Guntur",
    state: "Andhra Pradesh",
    website: "https://www.littlesistersofthepoorindia.org",
  },
  {
    slug: "lsp-jabalpur",
    name: "Little Sisters of the Poor — Home for the Aged, Jabalpur",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Jabalpur",
    district: "Jabalpur",
    state: "Madhya Pradesh",
    website: "https://www.littlesistersofthepoorindia.org",
  },
  {
    slug: "lsp-coonoor",
    name: "Little Sisters of the Poor — Home for the Aged, Coonoor",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Coonoor",
    district: "Nilgiris",
    state: "Tamil Nadu",
    website: "https://www.littlesistersofthepoorindia.org",
  },

  /* ---- SOS Children's Villages of India — family-based long-term care for
     children who have lost parental care (india's largest self-implementing
     childcare NGO, since 1964). Locations from soschildrensvillages.in. ---- */
  {
    slug: "sos-bengaluru",
    name: "SOS Children's Village, Bengaluru",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-bangalore/",
  },
  {
    slug: "sos-chennai",
    name: "SOS Children's Village, Chennai",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-chennai/",
  },
  {
    slug: "sos-hyderabad",
    name: "SOS Children's Village, Hyderabad",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Hyderabad",
    district: "Hyderabad",
    state: "Telangana",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-hyderabad/",
  },
  {
    slug: "sos-kolkata",
    name: "SOS Children's Village, Kolkata",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-kolkata/",
  },
  {
    slug: "sos-bhopal",
    name: "SOS Children's Village, Bhopal",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Bhopal",
    district: "Bhopal",
    state: "Madhya Pradesh",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-bhopal/",
  },
  {
    slug: "sos-thrissur",
    name: "SOS Children's Village, Thrissur",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Thrissur",
    district: "Thrissur",
    state: "Kerala",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-thrissur/",
  },

  /* ---- HelpAge India — Senior Care Homes (model homes for disadvantaged
     elders). From helpageindia.org/our-work/agecare/senior-care-homes/. ---- */
  {
    slug: "helpage-patiala",
    name: "HelpAge India — Senior Care Home, Patiala",
    careCategorySlug: "old-age-homes",
    category: "Senior care home (charitable)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential elder care", "Medical care"],
    city: "Patiala",
    district: "Patiala",
    state: "Punjab",
    website: "https://www.helpageindia.org/our-work/agecare/senior-care-homes/",
  },
  {
    slug: "helpage-gurdaspur",
    name: "HelpAge India — Senior Care Home, Gurdaspur",
    careCategorySlug: "old-age-homes",
    category: "Senior care home (charitable)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential elder care", "Medical care"],
    city: "Gurdaspur",
    district: "Gurdaspur",
    state: "Punjab",
    website: "https://www.helpageindia.org/our-work/agecare/senior-care-homes/",
  },
  {
    slug: "helpage-cuddalore",
    name: "HelpAge India — Senior Care Home, Cuddalore",
    careCategorySlug: "old-age-homes",
    category: "Senior care home (charitable)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential elder care", "Medical care"],
    city: "Cuddalore",
    district: "Cuddalore",
    state: "Tamil Nadu",
    website: "https://www.helpageindia.org/our-work/agecare/senior-care-homes/",
  },
  {
    slug: "helpage-kolkata",
    name: "HelpAge India — Senior Care Home, Kolkata",
    careCategorySlug: "old-age-homes",
    category: "Senior care home (charitable)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential elder care", "Medical care"],
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    website: "https://www.helpageindia.org/our-work/agecare/senior-care-homes/",
  },

  /* ---- Ramakrishna Math, Barisha — Home for the Aged (Kolkata). ---- */
  {
    slug: "rk-barisha-kolkata",
    name: "Ramakrishna Math Barisha — Home for the Aged, Kolkata",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential care", "Medical care"],
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    website: "https://ramakrishnamathbarisha.com/old-age-home/",
  },

  /* ---- Mental health / psychiatric rehabilitation ---- */
  {
    slug: "banyan-chennai",
    name: "The Banyan — Emergency Care & Recovery Centre, Chennai",
    careCategorySlug: "psychiatric-rehabilitation",
    category: "Mental health care & recovery (homeless / destitute)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Emergency mental health care", "Inpatient & recovery care", "Rehabilitation & reintegration"],
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    website: "https://thebanyan.org/",
  },
  {
    slug: "rfs-bangalore",
    name: "Richmond Fellowship Society (India), Bengaluru — Psychiatric Rehabilitation",
    careCategorySlug: "psychiatric-rehabilitation",
    category: "Psychiatric rehabilitation (halfway / long-stay / day care)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Halfway home", "Long-stay home", "Day-care rehabilitation"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://www.rfsbangalore.ngo/",
  },
  {
    slug: "rfs-vishwas-delhi",
    name: "Richmond Fellowship Society (Vishwas), Delhi-NCR — Psychiatric Rehabilitation",
    careCategorySlug: "psychiatric-rehabilitation",
    category: "Psychiatric rehabilitation (halfway home)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Halfway home", "Psychosocial rehabilitation"],
    address: "Knowledge Park III, Greater Noida",
    city: "Greater Noida",
    district: "Gautam Buddha Nagar",
    state: "Uttar Pradesh",
    pincode: "201310",
    website: "https://rfsdelhi.in/",
  },
  {
    slug: "rfs-lucknow",
    name: "Richmond Fellowship Society (India), Lucknow — Psychiatric Rehabilitation",
    careCategorySlug: "psychiatric-rehabilitation",
    category: "Psychiatric rehabilitation",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Psychosocial rehabilitation"],
    city: "Lucknow",
    district: "Lucknow",
    state: "Uttar Pradesh",
    website: "https://rfsindia.ngo/",
  },

  /* ---- Women's support & shelter ---- */
  {
    slug: "snehalaya-ahmednagar",
    name: "Snehalaya — Snehadhar Women's Refuge, Ahmednagar",
    careCategorySlug: "womens-support",
    category: "Shelter & rehabilitation for women in distress",
    gender: "female",
    residential: true,
    costType: "free",
    services: ["Shelter", "Counselling", "Rehabilitation", "Support for trafficking/violence survivors"],
    city: "Ahmednagar",
    district: "Ahmednagar",
    state: "Maharashtra",
    website: "https://www.snehalaya.org/snehadhar",
  },
  {
    slug: "snehalaya-pune",
    name: "Snehalaya — Snehadhar, Pune",
    careCategorySlug: "womens-support",
    category: "Shelter & rehabilitation for women in distress",
    gender: "female",
    residential: true,
    costType: "free",
    services: ["Shelter", "Counselling", "Rehabilitation"],
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    website: "https://www.snehalaya.org/post/snehadhar-pune",
  },
  {
    slug: "swayam-kolkata",
    name: "Swayam, Kolkata — Support for Women Facing Violence",
    careCategorySlug: "womens-support",
    category: "Support services for women affected by violence",
    gender: "female",
    residential: false,
    costType: "free",
    services: ["Counselling", "Legal support", "Shelter referral", "Vocational support"],
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    website: "https://www.swayam.info/",
  },
  {
    slug: "shakti-shalini-delhi",
    name: "Shakti Shalini — Pehchan Shelter Home, Delhi",
    careCategorySlug: "womens-support",
    category: "Shelter home for women in distress",
    gender: "female",
    residential: true,
    costType: "free",
    services: ["Shelter", "Crisis intervention", "Counselling", "Helpline"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://shaktishalini.org/pehchan-shelter-home/",
  },
  {
    slug: "maher-pune",
    name: "Maher — Home for Destitute Women, Men & Children, near Pune",
    careCategorySlug: "womens-support",
    category: "Interfaith home for the destitute (women, children, mentally ill)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Shelter", "Rehabilitation", "Care for destitute & mentally ill", "Child support"],
    address: "Vadhu Budruk",
    city: "Vadhu Budruk",
    district: "Pune",
    state: "Maharashtra",
    website: "https://maherashram.org/",
  },
  {
    slug: "sneha-mumbai",
    name: "SNEHA — Women & Children (Violence Prevention & Response), Mumbai",
    careCategorySlug: "womens-support",
    category: "Support for women & children facing violence",
    gender: "female",
    residential: false,
    costType: "free",
    services: ["Crisis intervention", "Counselling", "Community outreach", "Health support"],
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    website: "https://snehamumbai.org/",
  },

  /* ---- Disability rehabilitation & special education ---- */
  {
    slug: "bpa-ahmedabad",
    name: "Blind People's Association (BPA), Ahmedabad",
    careCategorySlug: "therapy-rehab-centers",
    category: "Comprehensive disability rehabilitation & special education",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Special education", "Rehabilitation", "Skill training", "Community-based rehabilitation"],
    city: "Ahmedabad",
    district: "Ahmedabad",
    state: "Gujarat",
    website: "https://bpaindia.org/",
  },
  {
    slug: "nab-delhi",
    name: "National Association for the Blind (NAB), Delhi",
    careCategorySlug: "therapy-rehab-centers",
    category: "Rehabilitation & education for the visually impaired",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Early intervention", "Inclusive schooling", "Rehabilitation (all ages)", "Home for the aged blind"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://www.nabdelhi.in/",
  },
  {
    slug: "amar-jyoti-delhi",
    name: "Amar Jyoti Charitable Trust, Delhi",
    careCategorySlug: "special-schools",
    category: "Integrated education & rehabilitation for children with disabilities",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Inclusive/integrated school", "Therapy & rehabilitation", "Vocational training"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://www.amarjyoti.org.in/",
  },
  {
    slug: "vidyasagar-chennai",
    name: "Vidya Sagar, Chennai — Disability (Cerebral Palsy & Special Needs)",
    careCategorySlug: "therapy-rehab-centers",
    category: "Therapy & rehabilitation for persons with disabilities",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Therapy", "Special education", "Assistive technology", "Caregiver training"],
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    website: "https://vidyasagar.co.in/",
  },

  /* ---- Widow support (Vrindavan) ---- */
  {
    slug: "madham-vrindavan",
    name: "Ma Dham Mahila Ashram (Guild for Service), Vrindavan",
    careCategorySlug: "widow-support-homes",
    category: "Shelter & rehabilitation for widows / abandoned women",
    gender: "female",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care", "Livelihood / income generation"],
    address: "Chaitanya Vihar, Vrindavan",
    city: "Vrindavan",
    district: "Mathura",
    state: "Uttar Pradesh",
    website: "https://guildforservice.org/",
  },
  {
    slug: "sulabh-widows-vrindavan",
    name: "Sulabh International — Widow Welfare, Vrindavan",
    careCategorySlug: "widow-support-homes",
    category: "Widow welfare & support (stipend, food, medical camps)",
    gender: "female",
    residential: true,
    costType: "free",
    services: ["Monthly stipend", "Food & nutrition", "Medical camps", "Support in government ashrams"],
    city: "Vrindavan",
    district: "Mathura",
    state: "Uttar Pradesh",
    website: "https://www.sulabhinternational.org/",
  },

  /* ---- Homeless / destitute & dying ---- */
  {
    slug: "moc-nirmal-hriday-kolkata",
    name: "Missionaries of Charity — Nirmal Hriday (Kalighat Home for the Dying), Kolkata",
    careCategorySlug: "homeless-rehabilitation",
    category: "Home for the sick & dying destitute",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Shelter for destitute", "Palliative & nursing care", "Meals"],
    address: "Kalighat",
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    website: "https://missionariesofcharity.org/what-we-do/homes-for-the-abandoned/",
  },
  {
    slug: "moc-prem-dan-kolkata",
    name: "Missionaries of Charity — Prem Dan, Kolkata",
    careCategorySlug: "homeless-rehabilitation",
    category: "Home for the sick, destitute & mentally ill",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Shelter for destitute", "Care for sick & mentally ill", "Meals"],
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    website: "https://missionariesofcharity.org/what-we-do/homes-for-the-abandoned/",
  },

  /* ---- Dementia / Alzheimer's care — ARDSI chapters (day care, home care,
     caregiver support). National body based in Kochi with 22 chapters. ---- */
  {
    slug: "ardsi-cochin",
    name: "ARDSI — Alzheimer's & Related Disorders Society of India, Kochi (HQ)",
    careCategorySlug: "dementia-care",
    category: "Dementia / Alzheimer's care & caregiver support",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Dementia day-care", "Home care", "Caregiver support & training", "Memory clinic"],
    city: "Kochi",
    district: "Ernakulam",
    state: "Kerala",
    website: "https://www.alzheimer.org.in/",
  },
  {
    slug: "ardsi-delhi",
    name: "ARDSI — Alzheimer's & Related Disorders Society, New Delhi Chapter",
    careCategorySlug: "dementia-care",
    category: "Dementia / Alzheimer's care & caregiver support",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Dementia day-care", "Home care", "Caregiver support"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://ardsidelhi.org/",
  },
  {
    slug: "ardsi-kolkata",
    name: "ARDSI — Alzheimer's & Related Disorders Society, Kolkata (Calcutta) Chapter",
    careCategorySlug: "dementia-care",
    category: "Dementia / Alzheimer's care & caregiver support",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Dementia day-care", "Home care", "Caregiver support"],
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    website: "https://ardsikolkata.org/",
  },
  {
    slug: "ardsi-hyderabad",
    name: "ARDSI — Alzheimer's & Related Disorders Society, Hyderabad Deccan Chapter",
    careCategorySlug: "dementia-care",
    category: "Dementia / Alzheimer's care & caregiver support",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Dementia day-care", "Home care", "Caregiver support"],
    city: "Hyderabad",
    district: "Hyderabad",
    state: "Telangana",
    website: "https://ardsi.org/chapters.php",
  },
  {
    slug: "ardsi-bengaluru",
    name: "ARDSI — Alzheimer's & Related Disorders Society, Bengaluru Chapter",
    careCategorySlug: "dementia-care",
    category: "Dementia / Alzheimer's care & caregiver support",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Dementia day-care", "Home care", "Caregiver support"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://ardsi.org/chapters.php",
  },
  {
    slug: "ardsi-jaipur",
    name: "ARDSI — Alzheimer's & Related Disorders Society, Jaipur Chapter",
    careCategorySlug: "dementia-care",
    category: "Dementia / Alzheimer's care & caregiver support",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Dementia day-care", "Home care", "Caregiver support"],
    city: "Jaipur",
    district: "Jaipur",
    state: "Rajasthan",
    website: "https://ardsi.org/chapters.php",
  },

  /* ---- Children — street & vulnerable children ---- */
  {
    slug: "salaam-baalak-delhi",
    name: "Salaam Baalak Trust, Delhi",
    careCategorySlug: "childrens-homes",
    category: "Children's homes & shelters for street children",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Education", "Vocational training", "Child helpline support"],
    address: "2nd Floor, DDA Community Centre, Chandi Wali Gali, Paharganj",
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    pincode: "110055",
    email: "contact@salaambaalaktrust.org",
    website: "https://www.salaambaalaktrust.com/",
    verificationStatus: "phone_verified",
  },
  {
    slug: "udayan-care-delhi",
    name: "Udayan Care (Udayan Ghars), New Delhi",
    careCategorySlug: "childrens-homes",
    category: "Family-like children's homes (Udayan Ghars)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based residential care", "Education & mentorship", "Aftercare"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://www.udayancare.org/",
  },
  {
    slug: "butterflies-delhi",
    name: "Butterflies, Delhi — Street & Working Children",
    careCategorySlug: "open-shelters",
    category: "Open shelter & support for street/working children",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Contact points / night shelter", "Education", "Health", "Child rights"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://www.butterfliesngo.org/",
  },

  /* ---- Mental health / psychiatric care (more cities incl. North-East) ---- */
  {
    slug: "scarf-chennai",
    name: "SCARF India (Schizophrenia Research Foundation), Chennai",
    careCategorySlug: "psychiatric-rehabilitation",
    category: "Care & rehabilitation for severe mental disorders",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Psychiatric care", "Rehabilitation", "Day care", "Community mental health"],
    address: "R/7A, North Main Road, Anna Nagar West Extension",
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    website: "https://scarfindia.org/",
  },
  {
    slug: "cadabams-bengaluru",
    name: "Cadabam's Rehabilitation Centre, Bengaluru",
    careCategorySlug: "psychiatric-rehabilitation",
    category: "Mental health & psychosocial rehabilitation",
    gender: "all",
    residential: true,
    costType: "paid",
    services: ["Inpatient rehabilitation", "Psychiatric care", "De-addiction", "Psychosocial rehab"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://www.cadabams.org/",
  },
  {
    slug: "sangath-goa",
    name: "Sangath, Goa — Community Mental Health",
    careCategorySlug: "psychiatric-care",
    category: "Community mental health services",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Counselling & psychotherapy", "Child & adolescent mental health", "Community programs"],
    city: "Porvorim",
    district: "North Goa",
    state: "Goa",
    website: "https://sangath.in/",
  },
  {
    slug: "ashadeep-guwahati",
    name: "Ashadeep, Guwahati — Care for the 'Wandering' Mentally Ill",
    careCategorySlug: "psychiatric-rehabilitation",
    category: "Shelter, treatment & rehabilitation for the mentally ill",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Shelter & residential care", "Psychiatric treatment", "Rehabilitation & reintegration"],
    city: "Guwahati",
    district: "Kamrup Metropolitan",
    state: "Assam",
    website: "https://ashadeepindia.org/",
  },

  /* ---- Disability — special education & rehabilitation (more orgs) ---- */
  {
    slug: "adapt-mumbai",
    name: "ADAPT (formerly Spastics Society of India), Mumbai",
    careCategorySlug: "special-schools",
    category: "Special education & therapy (cerebral palsy, developmental disability)",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Special education", "Therapy (PT/OT/speech)", "Inclusive education", "Vocational training"],
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    website: "https://www.adaptssi.org/",
  },
  {
    slug: "deepalaya-delhi",
    name: "Deepalaya, Delhi — Education & Support for Underprivileged Children",
    careCategorySlug: "ngos-charitable",
    category: "Charitable NGO — education, disability & child support",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Education", "Special education", "Child & community development"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://www.deepalaya.org/",
  },

  /* ---- Assisted living, memory care & senior day-care ---- */
  {
    slug: "athulya-chennai",
    name: "Athulya Senior Care, Chennai — Assisted Living & Memory Care",
    careCategorySlug: "assisted-living",
    category: "Assisted living, dementia & rehabilitation care",
    gender: "all",
    residential: true,
    costType: "paid",
    services: ["Assisted living", "Memory / dementia care", "Rehabilitation", "Palliative care"],
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    website: "https://www.athulyaseniorcare.com/",
  },
  {
    slug: "athulya-bengaluru",
    name: "Athulya Senior Care, Bengaluru — Assisted Living & Memory Care",
    careCategorySlug: "assisted-living",
    category: "Assisted living, dementia & rehabilitation care",
    gender: "all",
    residential: true,
    costType: "paid",
    services: ["Assisted living", "Memory / dementia care", "Rehabilitation"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://www.athulyaseniorcare.com/",
  },
  {
    slug: "silver-innings-mumbai",
    name: "Silver Innings — A1 Snehanjali Dementia Care Home, Mumbai",
    careCategorySlug: "dementia-care",
    category: "Residential dementia / Alzheimer's care",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential dementia care", "Person-centred care", "Elder care"],
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    website: "https://www.silverinnings.com/",
  },
  {
    slug: "antara-dehradun",
    name: "Antara Senior Living (Eden), Dehradun",
    careCategorySlug: "assisted-living",
    category: "Senior living & assisted care community",
    gender: "all",
    residential: true,
    costType: "paid",
    services: ["Independent & assisted living", "Healthcare", "Wellness"],
    city: "Dehradun",
    district: "Dehradun",
    state: "Uttarakhand",
    website: "https://www.antaraseniorliving.com/",
  },
  {
    slug: "agewell-delhi",
    name: "Agewell Foundation, New Delhi — Elder Welfare & Support",
    careCategorySlug: "senior-day-care",
    category: "Elder welfare, support & helpline",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Elder support", "Counselling", "Awareness & advocacy"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://www.agewellfoundation.org/",
  },
  {
    slug: "seruds-kurnool",
    name: "SERUDS — Free Old Age Home, Kurnool",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable, for poor elders)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    address: "D.No. 46-740, Budhavarapeta, Beside Canara Bank",
    city: "Kurnool",
    district: "Kurnool",
    state: "Andhra Pradesh",
    pincode: "518002",
    phone: "9849977577",
    email: "info@serudsindia.org",
    website: "https://serudsindia.org/elders/",
    verificationStatus: "phone_verified",
  },
  {
    slug: "mathru-chaya-bengaluru",
    name: "Mathru Chaya Trust — Old Age Home, Bengaluru",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://www.mathruchayatrust.org/",
  },

  /* ---- Disability — national institutes (DEPwD) ---- */
  {
    slug: "niepid-secunderabad",
    name: "NIEPID — National Institute for the Empowerment of Persons with Intellectual Disabilities, Secunderabad",
    careCategorySlug: "therapy-rehab-centers",
    category: "National institute — intellectual disability rehabilitation",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Assessment", "Early intervention", "Special education & training", "Rehabilitation services"],
    city: "Secunderabad",
    district: "Hyderabad",
    state: "Telangana",
    website: "https://niepid.nic.in/",
    verificationStatus: "government_verified",
  },
  {
    slug: "niepmd-chennai",
    name: "NIEPMD — National Institute for Empowerment of Persons with Multiple Disabilities, Chennai",
    careCategorySlug: "therapy-rehab-centers",
    category: "National institute — multiple disabilities rehabilitation",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Assessment & diagnosis", "Therapy", "Special education", "Assistive technology"],
    address: "East Coast Road, Muttukadu",
    city: "Chennai",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    website: "https://niepmd.nic.in/",
    verificationStatus: "government_verified",
  },
  {
    slug: "ayjnishd-mumbai",
    name: "AYJNISHD — National Institute of Speech & Hearing Disabilities, Mumbai",
    careCategorySlug: "therapy-rehab-centers",
    category: "National institute — speech & hearing disabilities",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Audiology & speech therapy", "Assessment", "Rehabilitation", "Assistive devices"],
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    website: "https://ayjnihh.nic.in/",
    verificationStatus: "government_verified",
  },

  /* ---- Children — Don Bosco street-children shelters ---- */
  {
    slug: "shelter-don-bosco-mumbai",
    name: "Shelter Don Bosco, Mumbai — Street Children",
    careCategorySlug: "childrens-homes",
    category: "Shelter & rehabilitation for street children",
    gender: "male",
    residential: true,
    costType: "free",
    services: ["Residential shelter", "Education", "Vocational training", "Reintegration"],
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    website: "https://www.shelterdonbosco.org/",
  },
  {
    slug: "don-bosco-navajeevan-hyderabad",
    name: "Don Bosco Navajeevan, Hyderabad — Street Children",
    careCategorySlug: "childrens-homes",
    category: "Shelter & rehabilitation for street children",
    gender: "male",
    residential: true,
    costType: "free",
    services: ["Residential shelter", "Meals & medical care", "Education", "Vocational training"],
    city: "Hyderabad",
    district: "Hyderabad",
    state: "Telangana",
    website: "https://dbnjhyd.org/",
  },
  {
    slug: "bosco-bengaluru",
    name: "BOSCO (Bangalore Oniyavara Seva Coota) — Street & Working Children",
    careCategorySlug: "open-shelters",
    category: "Support & shelter for street / working children",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Contact & drop-in", "Night shelter", "Education", "Reintegration"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://boscoban.org/",
  },

  /* ---- Palliative / hospice care (free care for the terminally ill) ---- */
  {
    slug: "karunashraya-bengaluru",
    name: "Karunashraya (Bangalore Hospice Trust), Bengaluru",
    careCategorySlug: "ngos-charitable",
    category: "Palliative / hospice care (advanced cancer)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Inpatient hospice care", "Home-care", "Pain & palliative care"],
    address: "Old Airport–Varthur Main Road, Kundalahalli Gate, Marathahalli",
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    pincode: "560037",
    phone: "080-42685666",
    email: "info@karunashraya.org",
    website: "https://karunashraya.org/",
    verificationStatus: "phone_verified",
  },
  {
    slug: "pallium-india-trivandrum",
    name: "Pallium India, Thiruvananthapuram — Palliative Care",
    careCategorySlug: "ngos-charitable",
    category: "Palliative care & pain relief",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Home-care visits", "Outpatient clinic", "Pain relief", "Training", "Helpline +91 96458 84889"],
    city: "Thiruvananthapuram",
    district: "Thiruvananthapuram",
    state: "Kerala",
    phone: "+91-9645884889",
    website: "https://palliumindia.org/",
    verificationStatus: "phone_verified",
  },
  {
    slug: "cansupport-delhi",
    name: "CanSupport, New Delhi — Home-based Cancer Palliative Care",
    careCategorySlug: "ngos-charitable",
    category: "Palliative care (home-based, cancer)",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Home-care", "Outpatient clinic", "Day care", "Counselling"],
    address: "60/2D, Indian Oil Bhawan Compound, Yusuf Sarai",
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    pincode: "110016",
    phone: "011-41010539",
    email: "info@cansupport.org",
    website: "https://www.cansupport.org/",
    verificationStatus: "phone_verified",
  },

  /* ---- Homeless persons with mental illness ---- */
  {
    slug: "iswar-sankalpa-kolkata",
    name: "Iswar Sankalpa, Kolkata — Homeless Persons with Mental Illness",
    careCategorySlug: "psychiatric-rehabilitation",
    category: "Mental health care & rehabilitation for the homeless",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Street outreach", "Shelter homes", "Mental health treatment", "Reintegration & livelihood"],
    address: "19/3 Pitambar Ghatak Lane, Near Chetla Police Station",
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    pincode: "700027",
    phone: "9903942044",
    email: "info@isankalpa.org",
    website: "https://isankalpa.org/",
    verificationStatus: "phone_verified",
  },

  /* ---- Disability — education, rehabilitation & livelihood ---- */
  {
    slug: "samarthanam-bengaluru",
    name: "Samarthanam Trust for the Disabled, Bengaluru",
    careCategorySlug: "therapy-rehab-centers",
    category: "Disability — education, rehabilitation & livelihood",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Education & accommodation", "Vocational training", "Rehabilitation", "Placement"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://samarthanam.org/",
  },
  {
    slug: "enable-india-bengaluru",
    name: "EnAble India, Bengaluru — Disability Employment & Livelihood",
    careCategorySlug: "therapy-rehab-centers",
    category: "Disability — skills, employment & independent living",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Skill training", "Employment support", "Assistive aids for daily living"],
    city: "Bengaluru",
    district: "Bengaluru",
    state: "Karnataka",
    website: "https://www.enableindia.org/",
  },
  {
    slug: "sense-india-ahmedabad",
    name: "Sense India (Sense International India), Ahmedabad — Deafblindness",
    careCategorySlug: "therapy-rehab-centers",
    category: "Support & rehabilitation for deafblindness & multiple disabilities",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Early intervention", "Special education support", "Family training", "Advocacy"],
    city: "Ahmedabad",
    district: "Ahmedabad",
    state: "Gujarat",
    website: "https://www.senseintindia.org/",
  },

  /* ---- Children — protection, shelter & anti-trafficking ---- */
  {
    slug: "prayas-delhi",
    name: "Prayas (JAC Society), New Delhi — Child Protection & Shelter",
    careCategorySlug: "childrens-homes",
    category: "Child protection, shelter & vocational training",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential shelter", "Child protection", "Education", "Vocational training"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://www.prayaschildren.org/",
  },
  {
    slug: "prerana-mumbai",
    name: "Prerana, Mumbai — Children of Sex Workers & Anti-Trafficking",
    careCategorySlug: "childrens-homes",
    category: "Protection & residential care for at-risk children",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Night care / shelter", "Anti-trafficking", "Education support", "Vocational training"],
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    website: "https://www.preranaantitrafficking.org/",
  },
  {
    slug: "chetna-delhi",
    name: "Chetna, Delhi — Street-connected Children",
    careCategorySlug: "open-shelters",
    category: "Empowerment & support for street-connected children",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Outreach & drop-in", "Education", "Life skills", "Child participation"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://chetnango.org/",
  },
  {
    slug: "cry-mumbai",
    name: "CRY (Child Rights and You), Mumbai",
    careCategorySlug: "ngos-charitable",
    category: "Child-rights NGO (works via local partner NGOs)",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Child rights programmes", "Partner NGO support", "Advocacy"],
    city: "Mumbai",
    district: "Mumbai",
    state: "Maharashtra",
    website: "https://www.cry.org/",
  },

  /* ---- Disability — North-East India ---- */
  {
    slug: "shishu-sarothi-guwahati",
    name: "Shishu Sarothi, Guwahati — Children with Disabilities (North-East)",
    careCategorySlug: "therapy-rehab-centers",
    category: "Early intervention, therapy & special education (disability)",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Early intervention", "Therapy", "Special education", "Advocacy & training"],
    address: "Off Ramkrishna Mission Road, Birubari",
    city: "Guwahati",
    district: "Kamrup Metropolitan",
    state: "Assam",
    pincode: "781016",
    phone: "9707149810",
    email: "contactus@shishusarothi.org",
    website: "https://www.shishusarothi.org/",
    verificationStatus: "phone_verified",
  },
  {
    slug: "bethany-society-shillong",
    name: "Bethany Society, Shillong — Disability & Inclusion (Meghalaya)",
    careCategorySlug: "special-schools",
    category: "Inclusive education, livelihoods & disability support",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Inclusive education", "Special education", "Livelihoods", "Community-based rehabilitation"],
    city: "Shillong",
    district: "East Khasi Hills",
    state: "Meghalaya",
    website: "https://bethanysociety.org/",
  },

  /* ---- De-addiction & rehabilitation ---- */
  {
    slug: "ttk-hospital-chennai",
    name: "TTK Hospital (TT Ranganathan Foundation), Chennai — De-addiction",
    careCategorySlug: "rehabilitation-homes",
    category: "Alcohol & drug de-addiction and rehabilitation",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Detoxification", "Rehabilitation", "Counselling", "Aftercare"],
    city: "Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    website: "https://www.ttkhospital.com/",
  },
  {
    slug: "muktangan-pune",
    name: "Muktangan Rehabilitation Center, Pune — De-addiction",
    careCategorySlug: "rehabilitation-homes",
    category: "Alcohol & drug de-addiction and rehabilitation",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Detoxification", "Therapy & rehabilitation", "Counselling", "Aftercare"],
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    website: "https://www.muktangan.org/",
  },

  /* ---- Old-age homes — new states (Odisha, Jharkhand, Chhattisgarh) ---- */
  {
    slug: "smss-bhubaneswar",
    name: "Subhadra Mahatab Seva Sadan (SMSS) — Old Age Home, Bhubaneswar",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Bhubaneswar",
    district: "Khordha",
    state: "Odisha",
    website: "https://smssodisha.org/old-age-home/",
  },
  {
    slug: "senior-citizen-home-ranchi",
    name: "The Senior Citizen Home (Arya Gyan Prachar Samiti), Ranchi",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Ranchi",
    district: "Ranchi",
    state: "Jharkhand",
    website: "https://theseniorhome.org/",
  },
  {
    slug: "kalyani-raipur",
    name: "Kalyani (Remsheela Ki Kutiya) Old Age Home, Raipur",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Raipur",
    district: "Raipur",
    state: "Chhattisgarh",
    website: "https://www.kalyaniindia.org.in/",
  },

  /* ---- Disability special schools — new cities ---- */
  {
    slug: "deevena-vizag",
    name: "DEEVENA Special School & Autism Care, Visakhapatnam",
    careCategorySlug: "special-schools",
    category: "Special school (autism, intellectual & learning disabilities)",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Special education", "Occupational & physiotherapy", "Day care", "Vocational training"],
    city: "Visakhapatnam",
    district: "Visakhapatnam",
    state: "Andhra Pradesh",
    website: "http://www.deevenaspecialschool.in/",
  },
  {
    slug: "third-eye-coimbatore",
    name: "Third Eye Center, Coimbatore — Autism & Special School",
    careCategorySlug: "special-schools",
    category: "Special school & autism centre",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Autism care", "Special education", "Therapy"],
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    website: "https://www.thirdeyecenter.org/",
  },
  {
    slug: "nissarc-coimbatore",
    name: "NISSARC, Coimbatore — Special Needs & Therapy",
    careCategorySlug: "special-schools",
    category: "Special education & multidisciplinary therapy",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Special education", "Occupational therapy", "Physiotherapy", "Play therapy"],
    city: "Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    website: "https://nissarc.com/",
  },

  /* ---- SOS Children's Villages — additional locations (new states incl. J&K) ---- */
  {
    slug: "sos-srinagar",
    name: "SOS Children's Village, Srinagar",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Srinagar",
    district: "Srinagar",
    state: "Jammu & Kashmir",
    website: "https://www.soschildrensvillages.in/",
  },
  {
    slug: "sos-rourkela",
    name: "SOS Children's Village, Rourkela",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Rourkela",
    district: "Sundargarh",
    state: "Odisha",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-rourkela/",
  },
  {
    slug: "sos-tirupati",
    name: "SOS Children's Village, Tirupati",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Tirupati",
    district: "Tirupati",
    state: "Andhra Pradesh",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-tirupati/",
  },
  {
    slug: "sos-bhuj",
    name: "SOS Children's Village, Bhuj",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Bhuj",
    district: "Kachchh",
    state: "Gujarat",
    website: "https://www.soschildrensvillages.in/",
  },
  {
    slug: "sos-faridabad",
    name: "SOS Children's Village, Faridabad (Greenfields)",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Faridabad",
    district: "Faridabad",
    state: "Haryana",
    website: "https://www.soschildrensvillages.in/",
  },

  /* ---- Old-age home — Bihar ---- */
  {
    slug: "sarvangin-patna",
    name: "Sarvangin Vikas Samiti — Old Age Home, Patna",
    careCategorySlug: "old-age-homes",
    category: "Old-age Home (charitable)",
    gender: "all",
    residential: true,
    costType: "mixed",
    services: ["Residential care", "Meals", "Medical care"],
    city: "Patna",
    district: "Patna",
    state: "Bihar",
    website: "http://www.oldagehomebihar.org/",
  },

  /* ---- Disability special school — Delhi ---- */
  {
    slug: "tamana-delhi",
    name: "Tamana, New Delhi — Special Education (Intellectual & Developmental Disability)",
    careCategorySlug: "special-schools",
    category: "Special education & autism centre",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Special education", "Autism intervention", "Vocational training", "Therapy"],
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    website: "https://www.tamana.org/",
  },

  /* ---- SOS Children's Villages — more locations (new UT: Puducherry) ---- */
  {
    slug: "sos-puducherry",
    name: "SOS Children's Village, Puducherry",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Puducherry",
    district: "Puducherry",
    state: "Puducherry",
    website: "https://www.soschildrensvillages.in/where-we-work/sos-children-s-village-puducherry",
  },
  {
    slug: "sos-guwahati",
    name: "SOS Children's Village, Guwahati",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Guwahati",
    district: "Kamrup Metropolitan",
    state: "Assam",
    website: "https://www.soschildrensvillages.in/sos-childrens-village-guwahati/",
  },
  {
    slug: "sos-nagapattinam",
    name: "SOS Children's Village, Nagapattinam",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Nagapattinam",
    district: "Nagapattinam",
    state: "Tamil Nadu",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-nagapattinam/",
  },
  {
    slug: "sos-begusarai",
    name: "SOS Children's Village, Begusarai",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Begusarai",
    district: "Begusarai",
    state: "Bihar",
    website: "https://www.soschildrensvillages.in/sos-children-s-village-begusarai/",
  },
  {
    slug: "sos-jammu",
    name: "SOS Children's Village, Jammu",
    careCategorySlug: "childrens-homes",
    category: "Children's Home (family-based care)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Family-based child care", "Education", "Healthcare"],
    city: "Jammu",
    district: "Jammu",
    state: "Jammu & Kashmir",
    website: "https://www.soschildrensvillages.in/",
  },

  /* ---- Disability — Chandigarh (UT) ---- */
  {
    slug: "griid-chandigarh",
    name: "GRIID — Govt. Rehabilitation Institute for Intellectual Disabilities, Chandigarh",
    careCategorySlug: "therapy-rehab-centers",
    category: "Institute — intellectual disability assessment & rehabilitation",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Child development clinic", "Assessment", "Special education", "Therapy (speech/OT/PT)"],
    city: "Chandigarh",
    district: "Chandigarh",
    state: "Chandigarh",
    website: "https://www.griid.edu.in/",
    verificationStatus: "government_verified",
  },
  {
    slug: "sorem-chandigarh",
    name: "SOREM — Society for Rehabilitation of Mentally Challenged, Chandigarh",
    careCategorySlug: "special-schools",
    category: "Special school for intellectual disabilities",
    gender: "all",
    residential: false,
    costType: "mixed",
    services: ["Special education", "Vocational training", "Therapy"],
    city: "Chandigarh",
    district: "Chandigarh",
    state: "Chandigarh",
    website: "https://soremspecialchildren.org/",
  },

  /* ---- Elderly / destitute — Puducherry (UT) ---- */
  {
    slug: "sharon-society-puducherry",
    name: "Sharon Society (Snehan / Pushpagandhi Home), Puducherry",
    careCategorySlug: "old-age-homes",
    category: "Home for destitute / abandoned elders (and rescued orphans)",
    gender: "all",
    residential: true,
    costType: "free",
    services: ["Residential care for destitute elders", "Rescue & rehabilitation", "Meals", "Medical care"],
    city: "Puducherry",
    district: "Puducherry",
    state: "Puducherry",
    website: "https://sharonsociety.org/",
  },

  /* ---- Charitable service / healthcare — Arunachal Pradesh (North-East) ---- */
  {
    slug: "rkm-itanagar",
    name: "Ramakrishna Mission Hospital, Itanagar",
    careCategorySlug: "ngos-charitable",
    category: "Charitable hospital & service (for the poor & needy)",
    gender: "all",
    residential: false,
    costType: "free",
    services: ["Charitable healthcare", "Community service", "Relief work"],
    city: "Itanagar",
    district: "Papum Pare",
    state: "Arunachal Pradesh",
    website: "https://itanagar.rkmm.org/",
  },
];

async function geocode(r: Rec): Promise<{ lat: number; lng: number } | null> {
  const g = GAZETTEER[r.city.toLowerCase()];
  if (g) return { lat: g.lat, lng: g.lng };
  const q = [r.city, r.district, r.state, r.pincode].filter(Boolean).join(", ");
  try {
    const url =
      "https://nominatim.openstreetmap.org/search?" +
      new URLSearchParams({ q: `${q}, India`, format: "json", limit: "1", countrycodes: "in" });
    const res = await fetch(url, { headers: { "User-Agent": "india-care-setu/0.1 (starter seed)" } });
    if (!res.ok) return null;
    const data = (await res.json()) as Array<{ lat: string; lon: string }>;
    const first = data[0];
    if (!first) return null;
    return { lat: Number.parseFloat(first.lat), lng: Number.parseFloat(first.lon) };
  } catch {
    return null;
  }
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const client = postgres(DATABASE_URL!, { max: 1, prepare: false });
  const db = drizzle(client, { schema });
  try {
    const cats = await db
      .select({ id: careCategories.id, slug: careCategories.slug })
      .from(careCategories);
    const idBySlug = new Map(cats.map((c) => [c.slug, c.id]));

    // idempotent: clear previous starter rows
    await db.execute(sql`DELETE FROM facilities WHERE external_id LIKE 'starter:%'`);

    let geocoded = 0;
    for (const r of RECORDS) {
      const geo = await geocode(r);
      if (geo) geocoded++;
      await db.insert(facilities).values({
        externalId: `starter:${r.slug}`,
        name: r.name,
        careCategoryId: idBySlug.get(r.careCategorySlug),
        category: r.category,
        gender: r.gender,
        residential: r.residential,
        costType: r.costType,
        services: r.services,
        address: r.address,
        city: r.city,
        district: r.district,
        state: r.state,
        pincode: r.pincode,
        phone: r.phone,
        email: r.email,
        latitude: geo?.lat,
        longitude: geo?.lng,
        officialSourceUrl: r.website,
        retrievedAt: new Date(),
        verificationStatus: r.verificationStatus ?? "needs_verification",
        lastVerified: r.verificationStatus === "government_verified" ? new Date() : undefined,
      });
      console.log(`  + ${r.name}${geo ? "" : "  (not geocoded)"}`);
      if (!GAZETTEER[r.city.toLowerCase()]) await sleep(1100); // Nominatim rate limit
    }
    const govVerified = RECORDS.filter((r) => r.verificationStatus === "government_verified").length;
    const contactVerified = RECORDS.filter((r) => r.verificationStatus === "phone_verified").length;
    console.log(`✓ starter facilities: ${RECORDS.length} (geocoded ${geocoded}; ${govVerified} government_verified, ${contactVerified} contact_verified, rest needs_verification). Sourced from official websites.`);
  } finally {
    await client.end();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
